openapi: 3.0.2
info:
  title: 'R2RML implementation report'
  version: 0.1.0
x-walder-resources:
  root: ./
  views: views
  pipe-modules: pipeModules
  public: public
x-walder-datasources:
  - https://raw.githubusercontent.com/jatoledo/r2rml-implementation-report/main/test-cases/results.ttl
  - https://raw.githubusercontent.com/kg-construct/r2rml-implementation-report/main/test-cases/manifest.ttl # Descriptions of the test cases
paths:
  /:
    get:
      summary: Return report
      x-walder-query:
        graphql-query: >
          {
            id @single
            type(_:Assertion)
            test @single {
              identifier @single
              title @single
            }
            result @single {
              outcome @single
            }
            processor @single {
              name @single
              version @single
            }
          }
        json-ld-context: >
          {
            "earl": "http://www.w3.org/ns/earl#",
            "dcterms": "http://purl.org/dc/elements/1.1/",
            "doap": "http://usefulinc.com/ns/doap#",
            "Assertion": "earl:Assertion",
            "test": "earl:test",
            "result": "earl:result",
            "outcome": "earl:outcome",
            "processor": "earl:subject",
            "identifier": "dcterms:identifier",
            "title": "dcterms:title",
            "name": "doap:name",
            "version": "doap:release",
            "type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
          }
      responses:
        200:
          description: R2RML implementation report
          x-walder-input-text/html: index.liquid
